# Generated by Django 4.1.3 on 2022-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='to',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
