# Generated by Django 4.1.3 on 2022-11-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_confession_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='to',
        ),
        migrations.AddField(
            model_name='confession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
